// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6igvOOcyX3KBOjH8YswZRsLO3ICFD8mI',
    appId: '1:284518267165:web:bf1549075ceeb6a44b49f4',
    messagingSenderId: '284518267165',
    projectId: 'tutorial-firebase-def27',
    authDomain: 'tutorial-firebase-def27.firebaseapp.com',
    storageBucket: 'tutorial-firebase-def27.firebasestorage.app',
    measurementId: 'G-PH93KF0WYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMFyh3nlviWeIDnKwJvnqnurzsk9hwoFM',
    appId: '1:284518267165:android:c183b03e818493eb4b49f4',
    messagingSenderId: '284518267165',
    projectId: 'tutorial-firebase-def27',
    storageBucket: 'tutorial-firebase-def27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4WIOULmRCR9cTrzvKt9PwAmlWTfENfCE',
    appId: '1:284518267165:ios:da9ba5415ab3e88b4b49f4',
    messagingSenderId: '284518267165',
    projectId: 'tutorial-firebase-def27',
    storageBucket: 'tutorial-firebase-def27.firebasestorage.app',
    iosBundleId: 'com.example.firebaseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4WIOULmRCR9cTrzvKt9PwAmlWTfENfCE',
    appId: '1:284518267165:ios:da9ba5415ab3e88b4b49f4',
    messagingSenderId: '284518267165',
    projectId: 'tutorial-firebase-def27',
    storageBucket: 'tutorial-firebase-def27.firebasestorage.app',
    iosBundleId: 'com.example.firebaseFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6igvOOcyX3KBOjH8YswZRsLO3ICFD8mI',
    appId: '1:284518267165:web:ef8f5043c785f4824b49f4',
    messagingSenderId: '284518267165',
    projectId: 'tutorial-firebase-def27',
    authDomain: 'tutorial-firebase-def27.firebaseapp.com',
    storageBucket: 'tutorial-firebase-def27.firebasestorage.app',
    measurementId: 'G-79JRLYG2XG',
  );
}
